# Generated by Django 3.2.8 on 2021-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True)),
                ('base', models.CharField(max_length=50)),
                ('hora_inicio', models.CharField(max_length=6)),
                ('hora_termino', models.CharField(max_length=6)),
                ('tipo_brigada', models.CharField(max_length=25)),
                ('clave_de_unidad', models.IntegerField()),
                ('nombre_jefebrigada', models.CharField(max_length=45)),
                ('nombre_conductor', models.CharField(max_length=45)),
                ('numero_de_brigadistas', models.IntegerField()),
                ('numero_de_motosierristas', models.IntegerField()),
                ('numero_de_conductor', models.IntegerField()),
                ('personal_operativo', models.IntegerField()),
                ('patente', models.CharField(max_length=10)),
                ('motosierra', models.BooleanField()),
                ('motobomba', models.BooleanField()),
                ('stock_aero_base', models.IntegerField()),
                ('kit_meteorologico', models.BooleanField()),
                ('sector', models.CharField(max_length=50)),
                ('stock_despuma', models.IntegerField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
